name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  # if you use large files

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add Hugging Face remote and pull
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://ujju4518:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/ujju4518/Search_Engine_LLM
          git pull --rebase hf main || true  # avoid failure if no remote changes

      - name: Push to Hugging Face
        run: git push hf main
